### ISSUE TITLE
The types of 'common.type' are incompatible between these types.

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/adapter-core#215]
Building the common object with : 

```
                const common = {};
		common.name = stateAttr[name] !== undefined ? stateAttr[name].name || name : name;
		common.type = 'number';
		common.role = stateAttr[name] !== undefined ? stateAttr[name].role || 'state' : 'state';
		common.read = true;
		common.unit = stateAttr[name] !== undefined ? stateAttr[name].unit || '' : '';
		common.write = stateAttr[name] !== undefined ? stateAttr[name].write || false : false;
```

than having the extendObjectAsync function : 

```
			await this.extendObjectAsync(stateName, {
				type: 'state',
				common
			});
```

Gives type check error : 

![Schermafbeelding 2020-04-20 om 12 36 13](https://user-images.githubusercontent.com/7318445/79742711-88b62380-8303-11ea-9a1c-dddd77699d18.png)

As I give it the value "number", this check is wrong ?

**Comment by AlCalzone** [comment]
Eh, yes... Design limitation.
```js
common.type = 'number';
```
Infers the type `string`, not the literal type `"number"` (notice the quotes) because the `type` property is mutable. In theory, between this assignment and the call to `extendObjectAsync` the type could be changed to something else that is not valid.

You should be able to help the type checker this way:
```js
/** @type {ioBroker.StateCommon} */
const common = {};
// ... same as before ...
```
This has the additional benefit that it tells you if you do a typo or assign an invalid type, e.g. this:
![grafik](https://user-images.githubusercontent.com/17641229/79752133-1732a100-8314-11ea-8883-32e86120b864.png)

**Comment by AlCalzone** [comment]
Or you could just put it all into one method call:
![grafik](https://user-images.githubusercontent.com/17641229/79752604-e56e0a00-8314-11ea-8772-47b5c60275d2.png)

**Comment by DutchmanNL** [comment]
thank you clarifying I can live with that just need to rethink my personal code logic
As its an limitation by design, I will close here using the suggestions you made

**Comment by AlCalzone** [comment]
> just need to rethink my personal code logic

Or use the type annotation. I've raised https://github.com/microsoft/TypeScript/issues/38056 to see if this can be improved on the TypeScript side.
